CREATE TABLE authors (
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL UNIQUE,
    last_name VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE book_images (
    book_id BIGINT NOT NULL,
    images VARCHAR(255)
);

CREATE TABLE books (
    author_id BIGINT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL UNIQUE,
    publisher_id BIGINT,
    public_id UUID NOT NULL UNIQUE,
    isbn VARCHAR(255) NOT NULL UNIQUE,
    synopsis VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE books_genres (
    book_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (book_id, genre_id)
);

CREATE TABLE facilitators (
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL UNIQUE,
    last_name VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE genres (
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE newsletters (
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sent_at TIMESTAMP(6),
    public_id UUID NOT NULL UNIQUE,
    content VARCHAR(10000) NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('DRAFT','SCHEDULED','SENT')),
    subject VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE orders (
    total_amount NUMERIC(38,2) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    public_id UUID NOT NULL UNIQUE,
    status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING_PAYMENT','PROCESSING','SHIPPED','DELIVERED','CANCELLED','PARTIALLY_REFUNDED','REFUNDED')),
    PRIMARY KEY (id)
);

CREATE TABLE products (
    available_stock INTEGER,
    price NUMERIC(38,2) NOT NULL,
    total_stock INTEGER,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL UNIQUE,
    description VARCHAR(2000),
    image_url VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    sku VARCHAR(255) UNIQUE,
    type VARCHAR(255) NOT NULL CHECK (type IN ('BOOK','MERCH','WORKSHOP')),
    PRIMARY KEY (id)
);

CREATE TABLE order_items (
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(38,2) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    public_id UUID NOT NULL UNIQUE,
    status varchar(255) not null check (status in ('PENDING','PROCESSING','SHIPPED','FULFILLED','CANCELLED','RETURN_REQUESTED','RETURNED','REFUNDED')),
    PRIMARY KEY (id)
);

CREATE TABLE publishers (
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE users (
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL CHECK (role IN ('CLIENT','ADMIN')),
    PRIMARY KEY (id)
);

CREATE TABLE reviews (
    rating INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_item_id BIGINT NOT NULL UNIQUE,
    product_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    public_id UUID NOT NULL UNIQUE,
    comment VARCHAR(2000),
    PRIMARY KEY (id)
);

CREATE TABLE subscribers (
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    subscribed_at TIMESTAMP(6) NOT NULL,
    unsubscribed_at TIMESTAMP(6),
    public_id UUID NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE transactions (
    amount NUMERIC(38,2) NOT NULL,
    confirmed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    public_id UUID NOT NULL UNIQUE,
    payment_method VARCHAR(255) NOT NULL CHECK (payment_method IN ('MERCADO_PAGO')),
    payment_status VARCHAR(255) NOT NULL CHECK (payment_status IN ('PENDING','AUTHORIZED','COMPLETED','FAILED','EXPIRED','VOIDED','PARTIALLY_REFUNDED','REFUNDED','CHARGED_BACK')),
    provider_reference VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE workshop_images (
    workshop_id BIGINT NOT NULL,
    image_url VARCHAR(255)
);

CREATE TABLE workshops (
    capacity INTEGER NOT NULL,
    duration_minutes INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    datetime TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    facilitator_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL UNIQUE,
    public_id UUID NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('REGISTRATION_OPEN','IN_PROGRESS','COMPLETED','CANCELLED')),
    title VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);


ALTER TABLE book_images ADD CONSTRAINT fk_book_images_book
    FOREIGN KEY (book_id) REFERENCES books;

ALTER TABLE books ADD CONSTRAINT fk_books_author
    FOREIGN KEY (author_id) REFERENCES authors;

ALTER TABLE books ADD CONSTRAINT fk_books_product
    FOREIGN KEY (product_id) REFERENCES products;

ALTER TABLE books ADD CONSTRAINT fk_books_publisher
    FOREIGN KEY (publisher_id) REFERENCES publishers;

ALTER TABLE books_genres ADD CONSTRAINT fk_books_genres_genre
    FOREIGN KEY (genre_id) REFERENCES genres;

ALTER TABLE books_genres ADD CONSTRAINT fk_books_genres_book
    FOREIGN KEY (book_id) REFERENCES books;

ALTER TABLE order_items ADD CONSTRAINT fk_order_items_order
    FOREIGN KEY (order_id) REFERENCES orders;

ALTER TABLE order_items ADD CONSTRAINT fk_order_items_product
    FOREIGN KEY (product_id) REFERENCES products;

ALTER TABLE orders ADD CONSTRAINT fk_orders_user
    FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE reviews ADD CONSTRAINT fk_reviews_order_item
    FOREIGN KEY (order_item_id) REFERENCES order_items;

ALTER TABLE reviews ADD CONSTRAINT fk_reviews_product
    FOREIGN KEY (product_id) REFERENCES products;

ALTER TABLE reviews ADD CONSTRAINT fk_reviews_user
    FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE transactions ADD CONSTRAINT fk_transactions_order
    FOREIGN KEY (order_id) REFERENCES orders;

ALTER TABLE workshop_images ADD CONSTRAINT fk_workshop_images_workshop
    FOREIGN KEY (workshop_id) REFERENCES workshops;

ALTER TABLE workshops ADD CONSTRAINT fk_workshops_facilitator
    FOREIGN KEY (facilitator_id) REFERENCES facilitators;

ALTER TABLE workshops ADD CONSTRAINT fk_workshops_product
    FOREIGN KEY (product_id) REFERENCES products;


CREATE INDEX idx_books_author_id ON books (author_id);
CREATE INDEX idx_books_publisher_id ON books (publisher_id);
CREATE INDEX idx_books_genres_genre_id ON books_genres (genre_id);
CREATE INDEX idx_book_images_book_id ON book_images (book_id);
CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_order_items_product_id ON order_items (product_id);
CREATE INDEX idx_orders_user_id ON orders (user_id);
CREATE INDEX idx_reviews_product_id ON reviews (product_id);
CREATE INDEX idx_reviews_user_id ON reviews (user_id);
CREATE INDEX idx_workshop_images_workshop_id ON workshop_images (workshop_id);
CREATE INDEX idx_workshops_facilitator_id ON workshops (facilitator_id);

CREATE INDEX idx_products_type ON products (type);

CREATE INDEX idx_subscribers_active ON subscribers (email) WHERE unsubscribed_at IS NULL;
