CREATE TABLE product_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL UNIQUE,
    product_id BIGINT NOT NULL,
    provider VARCHAR(255) NOT NULL CHECK (provider IN ('CLOUDINARY', 'YOUTUBE')),
    provider_id VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL CHECK (type IN ('IMAGE', 'VIDEO')),
    url VARCHAR(255) NOT NULL,
    alt_text VARCHAR(255),
    position INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_product_media PRIMARY KEY (id)
);

ALTER TABLE product_media ADD CONSTRAINT fk_product_media_product
    FOREIGN KEY (product_id) REFERENCES products;

CREATE INDEX idx_product_media_product_id ON product_media (product_id);

DROP TABLE book_images;
DROP TABLE workshop_images;
ALTER TABLE products DROP COLUMN image_url;
