logging.level.org.hibernate.SQL=DEBUG
management.endpoint.health.show-details=always
spring.jpa.show-sql=true

spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=/app/schema.sql
spring.jpa.hibernate.ddl-auto=none
